vis_labels = tribble(
  ~ item, ~ tag, ~ prompt,  
    '01', 'aims.1', 'The knowledge produced by scientific research is valuable even when it has no practical applications.', 
    '02', 'aims.2', 'A primary aim of science is to improve our understanding of threats to human health and the environment.', 
    '03', 'aims.3', 'A primary aim of science is to develop new technology and stimulate economic growth.', 
    '04', 'coi.1', 'Scientists will report conclusions that they think will get them more grant money even if the data does not fully support that conclusion.', 
    '05', 'coi.2', 'Special interests can always find an scientist-for-hire who will support their point of view.', 
    '06', 'coi.3', 'Research carried out by private companies is less trustworthy than research carried out by public instutitions.', 
    '07', 'consensus.1', 'Progress in science happens when a lone dissenter challenges popular ideas.', 
    '08', 'consensus.2', 'Scientists rarely disagree with each other about the answers to scientific questions.', 
    '09', 'consensus.3', 'The consensus of the scientific community is based on social status and prestige rather than evidence.', 
    '10', 'factvalue.1', 'Moral and social values are the kinds of things that can be confirmed or challenged by scientific evidence.', 
    '11', 'factvalue.2', 'If scientific findings conflict with important values that we hold, it\'s appropriate to be skeptical of the science.', 
    '12', 'factvalue.3', 'Someone\'s moral and social values are more like their taste in music than scientific facts.', 
    '13', 'fallible.1', 'Once a scientific theory has been established, it is never changed.', 
    '14', 'fallible.2', 'When a scientific theory changes or is revised, it means that the research that went into it initially was flawed.', 
    '15', 'fallible.3', 'Scientific findings can be good enough to act on even when they\'re not entirely certain. ', 
    '16', 'ir.1', 'Standards of scientific evidence are different in different situations.', 
    '17', 'ir.2', 'Scientists are not responsible for harmful effects of the technologies they develop.', 
    '18', 'ir.3', 'When scientific research has potential consequences for society, scientists must take these consequences into account when drawing conclusions.' , 
    '19', 'nonsubj.1', 'The results of scientific studies are always ambiguous and require interpretation.', 
    '20', 'nonsubj.2', 'Good scientific research is always free of assumptions and speculation.', 
    '21', 'nonsubj.3', 'Scientific conclusions are never a matter of interpretation or judgment.', 
    '22', 'pluralism.1', 'Scientific investigations always require laboratory experiments.', 
    '23', 'pluralism.2', 'Scientific research is always conducted in the following order: 1. Observation, 2. Hypothesis, 3. Experiment, 4. Conclusion', 
    '24', 'pluralism.3', 'All scientists use the same strict requirements for determining when empirical data confirm a tested hypothesis.', 
    '25', 'scientism.1', 'Science is more reliable than any other way of producing knowledge.', 
    '26', 'scientism.2', 'Everyone, whatever their worldview, should accept evidence.based scientific conclusions', 
    '27', 'scientism.3', 'Science is the only source of justified belief or knowledge about ourselves and the world.', 
    '28', 'stdpt.1', 'A scientific understanding of the social word depends on the background of the scientists carrying out the research.', 
    '29', 'stdpt.2', 'People on the margins of society often have a unique understanding of that society that can benefit scientific research. ', 
    '30', 'stdpt.3', 'Science has a long history of ignoring the unique insights of women and people of color.', 
    '31', 'technocracy.1', 'Public policy should wait until all relevant scientific questions have been settled.', 
    '32', 'technocracy.2', 'When it comes to public policy, scientific evidence is more important than public opinion. ', 
    '33', 'technocracy.3', 'Scientists have too much influence over public policy today. ', 
    '34', 'vfi.1', 'Scientists are more objective than other people.', 
    '35', 'vfi.2', 'Scientists do not use imagination or creativity because doing so interferes with objectivity', 
    '36', 'vfi.3', 'The evaluation and acceptance of scientific results must not be influenced by social and ethical values.'
  ) |> 
  mutate(item = str_c('ViS', item))
